### ISSUE TITLE
Error in get_torrents method

### ISSUE THREAD

**Issue by chicc0** [tsunam/btn#1]
`>>> from btn import btn
>>> apikey = "xxxxxxxxxxxxxxxxxxxxxxxx"
>>> client = btn(apikey)
>>> data = {'series': 'Game of Thrones', 'origin': 'P2P', 'source': 'WEB'}
>>> client.get_torrents(data)
{'results': '0'}`

Any idea?

**Comment by JoshuaJackson-jobvite** [comment]
For this one I'd suggest breaking down your data object into its parts and layer them slowly. I did this in the case and the source: 'WEB' is causing the results to be 0. So it appears there are no web source files available for the series.

**Comment by tsunam** [comment]
For this one I'd suggest breaking down your data object into its parts and layer them slowly. I did this in the case and the source: 'WEB' is causing the results to be 0. So it appears there are no web source files available for the series.
